### ISSUE TITLE
Seznam lidí

### ISSUE THREAD

**Issue by janpanschab** [Lin84/project-sova#1]
Pomocí Reactu vypiš seznam uživatelů. 
Jako zdroj použij https://jsonplaceholder.typicode.com/users. JSON si zkopíruj do `src/tpl/layouts/default.nunj:51` do configu.

**Comment by janpanschab** [comment]
Až to budeš mít pushnutý, uzavři task a já na to mrknu.

**Comment by Lin84** [comment]
Ahoj, ano pushnem to hned ako to budem mat.

**Comment by Lin84** [comment]
Ahoj,

Musel som zmenit zopar pravidel (eslint,...) kvoli erroru: (pls see attachment
![screen shot 2016-11-16 at 11 27 11](https://cloud.githubusercontent.com/assets/7355572/20346925/00d5dce6-abff-11e6-8bc7-ae7fd2069eb7.png)
)
